//EEPROM 0
#define A_ALU (1<<0)
#define FLAGS_ALU (1<<1)
#define IP_CNT (1<<2)
#define SP_CNT (1<<3)
#define SP_DOWN (1<<4)
#define C_CNT (1<<5)
#define C_DOWN (1<<6)
//EEPROM 1
#define CIN (1<<8)
#define ALU_M (1<<9)
#define ALU_S0 (1<<10)
#define ALU_S1 (1<<11)
#define ALU_S2 (1<<12)
#define ALU_S3 (1<<13)
#define A_SHR (1<<14)
#define A_SHL (1<<15)
//EEPROM 2
#define OFFSET_CLR (1<<16)
#define STOP (1<<17)
#define CNT_CLR (1<<18)
#define WS_IR4 (1<<19)
#define WE (1<<20)
#define OS_IR4 (1<<21)
#define OS_IR0 (1<<22)
#define OE (1<<23)
//EEPROM 3
#define OS_0to4 24
#define OS0 (1<<24)
#define OS1 (1<<25)
#define OS2 (1<<26)
#define OS3 (1<<27)
#define WS_0to4 28
#define WS0 (1<<28)
#define WS1 (1<<29)
#define WS2 (1<<30)
#define WS3 (1<<31)

//COMBINATIONS
#define A_OE (OE)
#define B_OE (OE | OS0)
#define C_OE (OE | OS1)
#define D_OE (OE | OS1 | OS0)
#define E_OE (OE | OS2)
#define F_OE (OE | OS2 | OS0)
#define G_OE (OE | OS2 | OS1)
#define SP_OE (OE | OS2 | OS1 | OS0)
#define BP_OE (OE | OS3)
#define IP_OE (OE | OS3 | OS0)
#define FLAGS_OE (OE | OS3 | OS1)
#define MEM_OE (OE | OS3 | OS2 | OS0)

#define A_WE (WE)
#define B_WE (WE | WS0)
#define C_WE (WE | WS1)
#define D_WE (WE | WS1 | WS0)
#define E_WE (WE | WS2)
#define F_WE (WE | WS2 | WS0)
#define G_WE (WE | WS2 | WS1)
#define SP_WE (WE | WS2 | WS1 | WS0)
#define BP_WE (WE | WS3)
#define IP_WE (WE | WS3 | WS0)
#define FLAGS_WE (WE | WS3 | WS1)
#define BASE_WE (WE | WS3 | WS1 | WS0)
#define OFFSET_WE (WE | WS3 | WS2)
#define MEM_WE (WE | WS3 | WS2 | WS0)
#define IR_WE (WE | WS3 | WS2 | WS1)

#define OE_IR0 (OE | OS_IR0)
#define OE_IR4 (OE | OS_IR4)
#define WE_IR4 (WE | WS_IR4)


//FLAGS
#define NONE 0
#define CF (1<<0)
#define ZF (1<<1)
#define SF (1<<2)